### ISSUE TITLE
Minecart TODO list

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#247]
* [ ] Smaller model shape
* [ ] Update texture
* [ ] Players should sit in minecart
* [ ] Add minecart with chest
* [ ] Add minecart with chest
* [ ] Add minecart with chest

**Comment by kingoscargames** [comment]
why 3 minecarts with chest?

**Comment by kingoscargames** [comment]
also players should sit in boats

**Comment by tobyplowy** [comment]
@Wuzzy2 the player shuld also be able to push the minecart by walking in to it and not by left clicking It

The minecart should be destroyed when a player left clicks the minecart (you have to hit it a copple times to brake it) right clicking will make the player enter (ride) the Minecart to get out you use Sneek (crouch)

That's how it works in minecraft

**Comment by tobyplowy** [comment]
@Wuzzy2 also if they go diagonally they still move in a straight line 
Go to 0:55 in this vid for example
https://m.youtube.com/watch?v=6Of2PdPcpV0&feature=youtu.be

It took me 20 minutes to find this vid XD
