### ISSUE TITLE
Wearable pumpkin / head TODO list

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#270]
* [ ] Pumpkin doesn't make endermen angry
* [ ] Reduced mob detection range
* [ ] Obstructed view while wearing pumpkin
* [ ] Dispenser equips it on player/armor stand if nearby
* [ ] Currently, there are extra textures for the wearable pumpkin/heads but it would be better if they were automatically created, in order to reduce the number of textures

**Comment by kingoscargames** [comment]
The golems are not spawned with heads but with pumpkins/pumpkin light things (forgot their name lol).

**Comment by Wuzzy2** [comment]
Corrected. Golems can be spawned, but not the Wither (yet).
