### ISSUE TITLE
Boat TODO list

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#274]
* [ ] Tweak Physics
* [ ] Ultra-fast on ice
* [ ] Super-slow movement on solid blocks
* [ ] Boats can take damage and break
* [ ] Boats must sink when underwater (instead of rising)
* [ ] Attach up to 2 riders

http://minecraft.gamepedia.com/Boat

**Comment by tobyplowy** [comment]
@Wuzzy2 you shuld also be able to place and ride the boat on land (yes thats a real feature)

also going backwards in the boat doesent play the animation in minecraft (but that may be a bug)
