### ISSUE TITLE
Final biome TODO list

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#397]
* [ ] Mesa underground
* [ ] Higher mineshafts in Mesa
* [ ] Different mineshaft wood in Mesa
* [ ] Extreme Hills M: Grass blocks on top, larger patches, vegetation?
