### ISSUE TITLE
Anvils TODO

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#462]
* [ ] Handle enchantments
* [ ] Damage anvil after falling
* [ ] Bug: Dragging output item onto player inventory item destroys the player inventory item
* [ ] More sounds
* [ ] Do more stuff w/ renamed items
